language: node_js
node_js: node
services:
- postgres
before_script:
- psql -c 'create database "test-park-hopper";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: XTQab2zHRblPWUIkPiMdh3SaYXj5ttpDy3Qw/0nxY3Rsneywej3YdspVoWM0S6AMFzHJFVxoWZjx2feNzMEgxCksFfA0V5EPddwUYvILKh2HlRjZuhMESNDYE424WmGi5dja2LzMFwXhvfQ/DVLFBtSf8bJrWrJ4DSHfecT4wHWVd9eMg0Cujbm0SYfDbYFlLt0k9vsdfYKD4EuVc+gbsnlDjuf7EkJaMxBn03ZR7voFvKqJXNPYsMVrZli3oVYrbIRaxRqox0WkEs58yhZTQW4wyBjk3BX+j3FyWtegqUN+zQUE1PpR79Kb4esGiGyWENpQV0JiukBC8iaOyxcbE15jdmdChnISOJfwWvqWVptk6ih1GduLr1i68bPllvXaMBQc7s0n9VpQ2mZahLmINZnYUWDTHc/hhWgk3YuchpXOhWMSNgBoI4BLIkZIv4hcND9izzE0ZO3TpaTYFPTpWunShZsrN3Kac0Xmd976an7zF/HLe7d6pGbvFmOUprkZPU5aQ9rD+pEX09nqbG+J4c0vnHrONJcmbRokyxb2w+FDGSFRmbEHICLmIiIl0VVKTr9djtxMej55w3u8gMtdziaK9KRhSh+72n9dCYEyduOfYg1RPaIU7a0/sxow1KcwxfvaVKPGYB65fW5d2nrrKMKSSCr9Fv3RVwxiDgN6XX0=
  app: park-hopper
  on:
    repo: Ljyockey/park-hopper
